sudo: required
services:
  - docker
before_install:
  - docker pull openaddr/machine || true
  - docker build -f Dockerfile-machine -t openaddr/machine:latest .
  - docker build -f Dockerfile-testing -t openaddr/testing:latest .
script:
  # Postgres needs a little time
  - docker-compose up -d && sleep 15
  - docker-compose run machine python3 /usr/local/src/openaddr/test.py
